module.exports = [
  {
    id:0,
    name: "1",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
  {
    id:1,
    name: "2",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
  {
    id:2,
    name: "3",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
  {
    id:3,
    name: "4",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
  {
    id:4,
    name: "5",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
  {
    id:5,
    name: "6",
    color1: 'test',
    color2: 'test',
    color3: 'test',
    color4: 'test',
    color5: 'test',
  },
];